import mongoose from 'mongoose';
import fs from 'fs';
const env = fs.readFileSync('.env.local','utf8');
const uri = env.match(/^MONGODB_URI=(.*)$/m)[1].trim().replace(/^["']|["']$/g,'');
await mongoose.connect(uri);
const S = mongoose.connection.db.collection('emailschedules');
const rows = await S.aggregate([{$group:{_id:'$status',n:{$sum:1}}}]).toArray();
if (!rows.length) console.log('  예약 자체가 없음');
for (const r of rows) console.log('  ', String(r._id).padEnd(10), r.n);
console.log('  pending(곧 나갈 것):', await S.countDocuments({status:'pending'}));
await mongoose.disconnect();
